FROM python:3.12

WORKDIR /app
RUN pip install --no-cache-dir pip-tools
COPY back-register/requirements.in .
RUN pip-compile requirements.in && \
    pip-sync requirements.txt

COPY back-register/ .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
